// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaCH0Djfwq6hadjUffWdJkzxPRsrqfiE',
    appId: '1:330406185788:web:8265400dfad20221d96c39',
    messagingSenderId: '330406185788',
    projectId: 'quizapp-ea4bf',
    authDomain: 'quizapp-ea4bf.firebaseapp.com',
    storageBucket: 'quizapp-ea4bf.appspot.com',
    measurementId: 'G-3DMGTP2CQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBpGd6J60PtSNus6Qfr3BiMAxMSY6ljlI',
    appId: '1:330406185788:android:e8c0b8bd8cdcceb8d96c39',
    messagingSenderId: '330406185788',
    projectId: 'quizapp-ea4bf',
    storageBucket: 'quizapp-ea4bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZURxyCl7QpBJyaj0aMl8MnBQuk1GHKdE',
    appId: '1:330406185788:ios:6045f1a951bb72a9d96c39',
    messagingSenderId: '330406185788',
    projectId: 'quizapp-ea4bf',
    storageBucket: 'quizapp-ea4bf.appspot.com',
    iosBundleId: 'com.example.brainupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZURxyCl7QpBJyaj0aMl8MnBQuk1GHKdE',
    appId: '1:330406185788:ios:b9b7f59afd547b7cd96c39',
    messagingSenderId: '330406185788',
    projectId: 'quizapp-ea4bf',
    storageBucket: 'quizapp-ea4bf.appspot.com',
    iosBundleId: 'com.example.brainupApp.RunnerTests',
  );
}
